name: Example workflow for Gradle
on: workflow_dispatch
jobs:
  security: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: Run Snyk Monitor for Gradle
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
